version: 0.2

phases:
  pre-build:
    commands:
      - npm install
  
  build:
    commands:
      - npm run build
  
  post_build:
    commands:
      - aws s3 sync build/ s3://stock-website-application-first --delete
      - aws cloudfront create-invalidation --distribution-id E20LMYX5Q6R2IS --path /\*